### ISSUE TITLE
Permission request not triggered after adding peer 

### ISSUE THREAD

**Issue by bibash28** [airgap-it/beacon-ios-sdk#21] opened 2022-09-07 13:35 UTC
You can find code in "dev-bibash" branch
https://github.com/bibash28/beacon-ios-sdk/tree/dev-bibash

**Comment by bibash28** [comment] 2022-09-07 13:37
https://github.com/bibash28/beacon-ios-sdk/commit/a0713466275608c9c65b7e2a5b3239a70a4ac93f

**Comment by jsamol** [comment] 2022-11-07 15:24
I'm closing this issue since I received a message from the OP on Slack saying that the issue was no more and most probably it was caused by something in the OP's code.

**Closed by jsamol** 2022-11-07 15:24 UTC
